-- Criar extensão para UUID (se necessário)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Criar tabelas
CREATE TABLE public.picpay_user (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cnpj varchar(255) NULL,
    cpf varchar(255) NULL,
    createdat timestamp NULL,
    email varchar(255) NULL,
    encryptedpassword varchar(255) NULL,
    "type" varchar(255) NULL,
    updatedat timestamp NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT uk_user_cnpj UNIQUE (cnpj),
    CONSTRAINT uk_user_cpf UNIQUE (cpf)
);

CREATE TABLE public.picpay_transaction (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    "timestamp" timestamp NULL DEFAULT now(),
    value numeric(19,2) NULL,
    payee_id int8 NULL,
    payer_id int8 NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT fk_picpay_transaction_payer FOREIGN KEY (payer_id) REFERENCES picpay_user(id),
    CONSTRAINT fk_transaction_payee FOREIGN KEY (payee_id) REFERENCES picpay_user(id)
);

CREATE TABLE public.picpay_wallet (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    balance numeric(19,2) NULL,
    owner_id int8 NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id),
    CONSTRAINT fk_wallet_owner FOREIGN KEY (owner_id) REFERENCES picpay_user(id)
);

-- Inserir usuários
INSERT INTO public.picpay_user (cnpj, cpf, createdat, email, encryptedpassword, "type", updatedat)
VALUES (NULL, '12345678909', now(), 'user1@mail.com', 'passwrd', NULL, now());
INSERT INTO public.picpay_wallet (balance, owner_id)
VALUES (100, (SELECT id FROM picpay_user WHERE email = 'user1@mail.com'));

INSERT INTO public.picpay_user (cnpj, cpf, createdat, email, encryptedpassword, "type", updatedat)
VALUES (NULL, '50443669007', now(), 'user2@mail.com', 'passwrd', NULL, now());
INSERT INTO public.picpay_wallet (balance, owner_id)
VALUES (1000, (SELECT id FROM picpay_user WHERE email = 'user2@mail.com'));

-- Inserir comerciantes
INSERT INTO public.picpay_user (cnpj, cpf, createdat, email, encryptedpassword, "type", updatedat)
VALUES ('84261480000134', NULL, now(), 'shop1@mail.com', 'passwrd', 'SHOPKEEPER', now());
INSERT INTO public.picpay_wallet (balance, owner_id)
VALUES (0, (SELECT id FROM picpay_user WHERE email = 'shop1@mail.com'));

INSERT INTO public.picpay_user (cnpj, cpf, createdat, email, encryptedpassword, "type", updatedat)
VALUES ('31975787000130', NULL, now(), 'shop2@mail.com', 'passwrd', 'SHOPKEEPER', now());
INSERT INTO public.picpay_wallet (balance, owner_id)
VALUES (100, (SELECT id FROM picpay_user WHERE email = 'shop2@mail.com'));
